"""Central configuration for the IDP Workflow."""

import os
from pathlib import Path

# Azure Document Intelligence
AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT = os.getenv("AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT", "")
AZURE_DOCUMENT_INTELLIGENCE_KEY = os.getenv("AZURE_DOCUMENT_INTELLIGENCE_KEY", "")

# Azure Content Understanding
COGNITIVE_SERVICES_ENDPOINT = os.getenv("COGNITIVE_SERVICES_ENDPOINT", "")
COGNITIVE_SERVICES_KEY = os.getenv("COGNITIVE_SERVICES_KEY", "")
AZURE_AI_CU_API_VERSION = os.getenv("AZURE_AI_CU_API_VERSION", "2025-11-01")

# Azure OpenAI
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT", "")
AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY", "")
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT_NAME", "gpt-4.1")
AZURE_OPENAI_REASONING_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_REASONING_DEPLOYMENT_NAME", "o3-mini")
AZURE_OPENAI_API_VERSION = os.getenv("AZURE_OPENAI_API_VERSION", "2025-01-01-preview")

# SignalR
SIGNALR_HUB_NAME = "idpworkflow"
SIGNALR_CONNECTION_SETTING = "AzureSignalRConnectionString"

# Orchestration
HITL_TIMEOUT_HOURS = int(os.getenv("HITL_TIMEOUT_HOURS", "24"))

# Domains
DOMAINS_DIR = Path(__file__).parent / "domains"
